# Generated by Django 2.2.4 on 2019-08-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke_title', models.CharField(max_length=200)),
                ('joke', models.TextField(default='')),
                ('answer', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
